### ISSUE TITLE
Host side tooling?

### ISSUE THREAD

**Issue by t-moe** [tweedegolf/sequential-storage#20]
Hello Team Tweedgolf,
I wanted to ask whether there is already some host-side tooling to read/write flash memory written by a target using sequential-storage.

I'm on esp32c6 here and I'm currently using espflash to interact with the target. But I could also imagine to build such tooling based on probe-rs, in order to target more architectures...

**Comment by diondokter** [comment]
Hey, never thought about that.

What would you want to see?

Like being able to create a file in some format and flash the data from that file to the device so you can give an initial config to the device?

Or more something to inspect the current values?

**Comment by t-moe** [comment]
My usecase:
I want to configure my iot devices with a series of key-value pairs. Normally the config values are updated only over the air. But sometimes devices break in the field and are no longer reachable via internet. In that case the devices are shipped back to us and it would be nice if we could inspect their configuration with some host-side tools.

If I were on std, I would probably use something like https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_flash.html , which provides some python scripts on the host side.

---

Host side tooling wishlist, in descending priority :). 
- dump the current configuration (e.g. active key-value pairs) (CLI)
- being able to retrieve the value associated with a single key (CLI)
- being able to modify a single key (CLI)
- being able to write an initial config (e.g. csv/json) into the device (CLI)

Since key/value types are pretty unrestricted and not always printable, I understand a CLI might be difficult to realize...

**Comment by t-moe** [comment]
Hmm....., Yes.  Implementing the norflash traits seems like the most compatible/reasonable thing to do... 

And then, it would probably make sense to create a self-describing, serde-compatible data format, based on top of sequential-storage. And implement the CLI for that.

But, I really only wanted to know, whether there are some thoughts/tools in this direction. I don't have the expectation that you take action immediately here ;). 

Thank you!
(We can probably close this issue.)

**Comment by diondokter** [comment]
I'll keep it open because I do find it interesting. But yeah, I might not pick it up right away (or ever). Who knows

**Comment by diondokter** [comment]
I've thought about it and I don't think I can make a useful tool out of this...
