### ISSUE TITLE
Release 2.0.0 ?

### ISSUE THREAD

**Issue by HaoboGu** [tweedegolf/sequential-storage#46]
Hi! Is there a plan for a 2.0.0 release? My crate currently relies on master branch, hence cargo blocks me to release it to crates.io 😂 . 

I don't mean to push anything, just want to have some information about the release plan :D

**Comment by diondokter** [comment]
Oh cool what are you releasing?

The release is mostly just waiting on #39 since that will likely be a breaking change. Other than that I don't have any more breaking changes in mind...

**Comment by diondokter** [comment]
Oh, right, probably the rmk crate

**Comment by HaoboGu** [comment]
yeah, it's RMK crate.

Thanks for the reply!

**Comment by HaoboGu** [comment]
> @HaoboGu Hey there! Was tired of waiting so I just released the 2.0 version!

WOOOOOOOOOOOOOOOOOW, I'm going to update to 2.0.0 right now!
