### ISSUE TITLE
Add MSRV

### ISSUE THREAD

**Issue by HaoboGu** [tweedegolf/sequential-storage#55]
Now with new build.rs, sequential-storage doesn't compile on Rust versions below 1.77:

```
$ cargo build --release
   Compiling sequential-storage v2.0.2
error: unsupported output in build script of `sequential-storage v2.0.2`: `cargo::rustc-check-cfg=cfg(fuzzing_repro)`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
```

So it would be good to have a MSRV(Minimum Supported Rust Version) section in project readme

**Comment by diondokter** [comment]
Ah, I thought it would be ignored by older stables. But no
![image](https://github.com/tweedegolf/sequential-storage/assets/8545127/8c6b5efb-dde6-4d11-852b-b2432bbe6e2b)
(https://blog.rust-lang.org/2024/05/06/check-cfg.html)

Are you limited by upgrading your compiler version?
Very few people are so I'm quite anti MSRV. If I put anything in the readme it'd only be guaranteed the latest stable.
But I'm open to suggestions.

**Comment by diondokter** [comment]
CI is also configured to run on the latest stable right now

**Comment by HaoboGu** [comment]
> Are you limited by upgrading your compiler version?

No, but I do not always keep up-to-date with the latest version.

I have no preference of MSRV, anything like FAQs or just a hint is good enough (for me).

**Comment by diondokter** [comment]
Added it to the readme
