### ISSUE TITLE
Use with few, very large flash pages?

### ISSUE THREAD

**Issue by liamkinne** [tweedegolf/sequential-storage#62]
I would like to use this library with an STM32H7 that has 16x128kB flash pages. Is it possible/effective to use sequential-storage with only two pages?

The main limitation realistically is not using up too much program space, but the time it takes to erase a page being over 2 seconds.

**Comment by diondokter** [comment]
Hi, yeah those pages are huge and the word size is quite big as well. So not ideal. But it does work.

Two pages are enough. For the map that means you can only store 128kb of data as the other page is used as buffer. For queue you can fill up the entire 256kb.

The H7 has two flash banks. The 2 seconds erase is long and it stalls the processor too. However, I *think* that if your processor is running flash code at bank 1 and there's an erase going on at bank 2, it should not block code execution.

(It will still block if you provide a blocking flash impl or do a block_on call on the async function of course, I can't control that)

So yes, it'll run. It'll just take up way more flash space than you need and you need to figure out whether you can handle the erase time and it possibly blocking the code execution.

**Comment by diondokter** [comment]
Actually, just realized that the queue won't work for you because you don't have multiwrite flash...

Only map works for you.

You could also always add a cheap small flash chip to your board. But I don't know what you're using it for.

I hope this all answers your questions!

**Comment by liamkinne** [comment]
Thanks.

I've already written a small async-flash implementation for the H7 since stm32h7xx-hal doesn't yet support it.

Ultimately I will have to give it a go and see what results I get. I would have put an external flash chip in the design if I'd known about the page size. Currently we're just using a 16kB I2C eeprom to store configuration, but I can get rid of that in future revisions if this works out.
