### ISSUE TITLE
Support/use alloc::String and heapless::String for keys and values

### ISSUE THREAD

**Issue by yanshay** [tweedegolf/sequential-storage#67]
I want to use variable length strings as keys and values.
When checking for options I found that there is support for arrayvec String for the keys which seems to be similar heapless::String, but not for the values and for those there is support for u8 slices, is that indeed the case?

Is there anything that would prevent adding support for all string types mentioned (alloc heapless and arrayvec) to be supported for both keys and values? And also for all sorts of Vec types (heapless, alloc, arrayvec).

I'm willing to try and submit a PR for that if that's something that is possible to do without dealing with internals complexities.

**Comment by diondokter** [comment]
Hi, yeah that's possible, but it needs to be behind a feature flag (using alloc should be optional and disabled by default).

Note though that this isn't required to do. You can implement the `Key` trait on your own types that can have a string.
But I'd be open to a PR

**Comment by yanshay** [comment]
Thanks. Yes I can do that on my own types but Rust won't allow me to do that on types from another crait.

I'll try and if successful will submit a PR.

**Comment by yanshay** [comment]
I implemented the alloc String and Vec for Key and Value, but when I think of it, is there any point having the Key as String or Vec (or arrayvec alternatives for that matter)?
As there is no way to iterate over keys it would save memory and time to use a hash, won't it?

**Comment by diondokter** [comment]
Yeah hashing could work! But it'd have to have be a newtype
